\hypertarget{classpip_1_1exceptions_1_1_hash_error}{}\section{pip.\+exceptions.\+Hash\+Error Class Reference}
\label{classpip_1_1exceptions_1_1_hash_error}\index{pip.\+exceptions.\+Hash\+Error@{pip.\+exceptions.\+Hash\+Error}}


Inherits \hyperlink{classpip_1_1exceptions_1_1_installation_error}{pip.\+exceptions.\+Installation\+Error}.



Inherited by \hyperlink{classpip_1_1exceptions_1_1_directory_url_hash_unsupported}{pip.\+exceptions.\+Directory\+Url\+Hash\+Unsupported}, \hyperlink{classpip_1_1exceptions_1_1_hash_mismatch}{pip.\+exceptions.\+Hash\+Mismatch}, \hyperlink{classpip_1_1exceptions_1_1_hash_missing}{pip.\+exceptions.\+Hash\+Missing}, \hyperlink{classpip_1_1exceptions_1_1_hash_unpinned}{pip.\+exceptions.\+Hash\+Unpinned}, and \hyperlink{classpip_1_1exceptions_1_1_vcs_hash_unsupported}{pip.\+exceptions.\+Vcs\+Hash\+Unsupported}.

\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
def \hyperlink{classpip_1_1exceptions_1_1_hash_error_ad40d9767743dd1fe1dc4b6c0fd4da430}{body} (self)
\item 
\mbox{\Hypertarget{classpip_1_1exceptions_1_1_hash_error_ab3e17b635226fb645571c6a4ae67c4ec}\label{classpip_1_1exceptions_1_1_hash_error_ab3e17b635226fb645571c6a4ae67c4ec}} 
def {\bfseries \+\_\+\+\_\+str\+\_\+\+\_\+} (self)
\end{DoxyCompactItemize}
\subsection*{Static Public Attributes}
\begin{DoxyCompactItemize}
\item 
\mbox{\Hypertarget{classpip_1_1exceptions_1_1_hash_error_a427b4d318130b8d1f635881cd0ed7072}\label{classpip_1_1exceptions_1_1_hash_error_a427b4d318130b8d1f635881cd0ed7072}} 
{\bfseries req} = None
\item 
\mbox{\Hypertarget{classpip_1_1exceptions_1_1_hash_error_aafb16061daf0656dc2d9874e66c0370b}\label{classpip_1_1exceptions_1_1_hash_error_aafb16061daf0656dc2d9874e66c0370b}} 
string {\bfseries head} = \textquotesingle{}\textquotesingle{}
\end{DoxyCompactItemize}


\subsection{Detailed Description}
\begin{DoxyVerb}A failure to verify a package against known-good hashes

:cvar order: An int sorting hash exception classes by difficulty of
    recovery (lower being harder), so the user doesn't bother fretting
    about unpinned packages when he has deeper issues, like VCS
    dependencies, to deal with. Also keeps error reports in a
    deterministic order.
:cvar head: A section heading for display above potentially many
    exceptions of this kind
:ivar req: The InstallRequirement that triggered this error. This is
    pasted on after the exception is instantiated, because it's not
    typically available earlier.\end{DoxyVerb}
 

\subsection{Member Function Documentation}
\mbox{\Hypertarget{classpip_1_1exceptions_1_1_hash_error_ad40d9767743dd1fe1dc4b6c0fd4da430}\label{classpip_1_1exceptions_1_1_hash_error_ad40d9767743dd1fe1dc4b6c0fd4da430}} 
\index{pip\+::exceptions\+::\+Hash\+Error@{pip\+::exceptions\+::\+Hash\+Error}!body@{body}}
\index{body@{body}!pip\+::exceptions\+::\+Hash\+Error@{pip\+::exceptions\+::\+Hash\+Error}}
\subsubsection{\texorpdfstring{body()}{body()}}
{\footnotesize\ttfamily def pip.\+exceptions.\+Hash\+Error.\+body (\begin{DoxyParamCaption}\item[{}]{self }\end{DoxyParamCaption})}

\begin{DoxyVerb}Return a summary of me for display under the heading.

This default implementation simply prints a description of the
triggering requirement.

:param req: The InstallRequirement that provoked this error, with
    populate_link() having already been called\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+6/site-\/packages/pip/exceptions.\+py\end{DoxyCompactItemize}
