\hypertarget{classpluggy_1_1manager_1_1_plugin_validation_error}{}\section{pluggy.\+manager.\+Plugin\+Validation\+Error Class Reference}
\label{classpluggy_1_1manager_1_1_plugin_validation_error}\index{pluggy.\+manager.\+Plugin\+Validation\+Error@{pluggy.\+manager.\+Plugin\+Validation\+Error}}


Inherits Exception.

\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\mbox{\Hypertarget{classpluggy_1_1manager_1_1_plugin_validation_error_a528658dcafe009078c661442dda19642}\label{classpluggy_1_1manager_1_1_plugin_validation_error_a528658dcafe009078c661442dda19642}} 
def {\bfseries \+\_\+\+\_\+init\+\_\+\+\_\+} (self, plugin, message)
\end{DoxyCompactItemize}
\subsection*{Public Attributes}
\begin{DoxyCompactItemize}
\item 
\mbox{\Hypertarget{classpluggy_1_1manager_1_1_plugin_validation_error_add5b9adf796c8c30226ecc8b03097026}\label{classpluggy_1_1manager_1_1_plugin_validation_error_add5b9adf796c8c30226ecc8b03097026}} 
{\bfseries plugin}
\end{DoxyCompactItemize}


\subsection{Detailed Description}
\begin{DoxyVerb}plugin failed validation.

:param object plugin: the plugin which failed validation,
    may be a module or an arbitrary object.
\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+6/site-\/packages/pluggy/manager.\+py\end{DoxyCompactItemize}
